version: "3.9"

networks:
  remito_net:

services:
  api:
    build: ./api
    container_name: api
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - db
      - ocr
    volumes:
      - ./guardados:/app/guardados

  frontend:
    build: ./app_web
    container_name: appweb
    ports:
      - "5000:5000"
    depends_on:
      - api

  ocr:
    build: ./ocr
    container_name: ocr

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: